version: '3'
services: 
  challenge1:   
    build: .
    ports:
      - "1337:80"
    volumes:
      - ./challenge1:/var/www/html
    restart: unless-stopped
  
  challenge2:
    build: .
    ports:
      - "1338:80"
    volumes:
      - ./challenge2:/var/www/html
    restart: unless-stopped

  challenge3:
    build: .
    ports:
      - "1339:80"
    volumes:
      - ./challenge3:/var/www/html
    restart: unless-stopped

  challenge4:
    build: .
    ports:
      - "1340:80"
    volumes:
      - ./challenge4:/var/www/html
    restart: unless-stopped

  challenge6:
    build: .
    ports:
      - "1342:80"
    volumes:
      - ./challenge6:/var/www/html
    restart: unless-stopped
